import React from 'react'

const welcome = () => (
    
    <section>
        <div id='bienvenida' className='anchor' style={{ scrollMarginTop: 100 }}></div>
          <h1>Bienvenidos al Encuentro Nacional de Arritmias</h1>
          <p> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum mollis molestie elementum. Donec cursus augue non nibh condimentum, sed lobortis tellus elementum. Proin quis volutpat metus. Suspendisse posuere ligula pellentesque, molestie tortor sit amet, laoreet sem. Phasellus sem ipsum, efficitur nec eros sit amet, elementum malesuada nisl. Maecenas maximus in lectus vitae semper. Fusce venenatis tempus eros non sodales. Nulla a felis vel turpis aliquam ultrices eu eu mi. Vestibulum finibus, tellus ac aliquam vehicula, erat purus pretium tellus, sit amet facilisis lorem augue et diam. Donec sollicitudin condimentum leo, nec ornare ipsum eleifend id. Aenean eget porttitor felis. Sed facilisis justo a lacus tempus, egestas facilisis ante aliquet. Morbi nec efficitur nibh, ac feugiat nulla. Etiam aliquam orci a nisi sollicitudin, vel tincidunt elit lacinia.</p>
          <p>Proin semper mi nulla, eu hendrerit diam sodales vitae. Donec bibendum nunc vitae tortor hendrerit, et elementum metus laoreet. Donec sodales nibh sit amet enim sollicitudin sollicitudin. Mauris nec scelerisque lacus. Maecenas euismod efficitur massa, ut finibus lorem. Nunc ut est quis ipsum malesuada vehicula. Praesent ut nisl feugiat, eleifend erat ac, tempor ligula. Praesent viverra efficitur ligula, et facilisis tellus gravida ac. Praesent et dolor orci. Integer vitae orci ut est sagittis pretium. Vivamus tempor ante eget diam cursus tincidunt. Praesent consequat mollis erat nec faucibus. Ut mollis justo nec facilisis congue. Pellentesque a odio eu mi cursus blandit non vitae enim. Etiam tincidunt mauris et justo vulputate suscipit.</p>
          <p>Donec finibus, lectus non dictum commodo, nisi dui scelerisque libero, nec aliquam massa mauris vel ligula. Nunc quis varius tellus. Maecenas pretium est eget nisl ultrices, sed malesuada metus ultrices. Mauris pharetra, ipsum eu gravida egestas, erat orci maximus nisl, in rhoncus eros dui at felis. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Aliquam pharetra porta sem, eu facilisis massa pellentesque id. Ut euismod felis ut ex tempus, ut condimentum sapien blandit. Sed in posuere tortor. Nulla eget tempus nibh, sit amet laoreet nisl.</p>
          
          <p>Duis placerat mauris ut purus tincidunt mollis. Sed sed mauris eu erat molestie cursus ac ut nibh. Aliquam et elit et augue pulvinar congue sit amet non dui. Vivamus ornare sem eu lacus pulvinar commodo in a urna. Vestibulum hendrerit, lectus sit amet iaculis viverra, diam ipsum tristique ante, et venenatis ligula mi in turpis. In imperdiet eros vel mollis porttitor. Praesent congue ante at luctus elementum. Suspendisse sodales felis ornare libero gravida, non vulputate ex pulvinar. Nullam quis egestas dolor. Ut at lacinia mi, quis volutpat ante. Vestibulum quam dolor, bibendum eu risus a, pretium euismod arcu. Quisque posuere convallis dolor, sit amet porta elit. Donec dictum eros odio, nec tempus odio vestibulum ac. Nullam pretium ornare dolor et pellentesque. Pellentesque at ipsum ac neque maximus mattis in nec neque. Etiam id fringilla magna. </p>
    </section>

)

export default welcome
